name = "letterboxd-backend"
main = "config/wsgi.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

# Cloudflare D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "letterboxd-db"
database_id = "f5b8f454-ef0a-4d42-a179-90ccc259d573"

# Preview database for development
preview_database_id = "f5b8f454-ef0a-4d42-a179-90ccc259d573"

[env.production]
vars = { DEBUG = "False" }

# Environment variables
[vars]
DEBUG = "True"
TMDB_API_KEY = ""  # Add your TMDb API key here
